#version: "3.7"

networks:
  loki-network:

services:
  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      # Cổng 3100 là cổng mặc định mà winston-loki gửi logs đến
      - "3100:3100" 
    command: -config.file=/etc/loki/config.yml
    volumes:
      - ./loki-config.yml:/etc/loki/config.yml
      - loki-data:/loki
    networks:
      - loki-network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      # Cổng 3000 là cổng mặc định của Grafana (Nếu trùng với NestJS, có thể đổi thành 3001)
      - "3001:3000" 
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true # Bật chế độ anonymous để dễ truy cập
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      - loki-network

  db:
    image: nxt964/sakila-mysql:latest
    container_name: mysql_db
    restart: always
    ports:
      - "3306:3306"
    environment:
      # This is the variable the error message is asking for
      MYSQL_ROOT_PASSWORD: rootpassword

      # These are still good practice for your app to connect with
      MYSQL_DATABASE: sakila
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  loki-data:
  grafana-data:
  mysql-data: